#
# Docker compose configuration file for NIST Pages PDF support.
#
# From https://github.com/bspk/nistpages-docker/blob/master/pdf/docker-compose-pdf.yml
#

version: '3'

services:
  pdfrender:
    image: csd773/csd773-nistpages-docker:newtexlive@sha256:c96d4a86f13a21165c7e8870f5dab7dc1ace4f7d2628889fce081d5254d62ee1
    volumes:
        - .:/opt/source
    environment:
        - "PDFTARGET=${PDFTARGET}"
        - PYTHONUNBUFFERED=1
    command: python /opt/pdf/preprocess-pdf.py
    working_dir: /opt/source
    
