
name: build-release

on:
  release:
    types:
      - created

permissions:
  contents: write
jobs:

  build-release-pdfs:
    # Use github-hosted runner
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out Repo
        uses: actions/checkout@v4

        # Build PDFs with docker    
      - name: Build the artifacts with the docker image
        run: docker compose -f docker-compose-pdf.yml up

      - name: Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          files: |
            _pdf/SP800-217/SP800-217.pdf